version: "3.4"
services:
  master:
    container_name: master
    build:
      dockerfile: Dockerfile
      context: ./master
    volumes:
      - "./master/app:/src/app"
    ports:
      - 3000:3000
      
  secondary_1:
    container_name: secondary_1
    build:
      dockerfile: Dockerfile
      context: ./secondary
    volumes:
      - "./secondary/app:/src/app"
    ports:
      - 6000

  secondary_2:
    container_name: secondary_2
    build:
      dockerfile: Dockerfile
      context: ./secondary
    volumes:
      - "./secondary/app:/src/app"
    ports:
      - 6000

#  toxiproxy:
#    image: shopify/toxiproxy
#    ports:
#      - 8574
#      - 5001
#      - 5002
#      - 6001
#      - 6002
#
#  mytoxiproxy-configurer:
#    build: 
#      context: ./toxiproxy
#      dockerfile: Dockerfile-toxiproxy-configurer
#    depends_on:
#      - toxiproxy