version: "3.4"
services:
  master:
    container_name: standalone_master
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - "./app:/src/app"
    ports:
      - 3000
    networks:
      - my-net

networks:
  my-net:
    driver: bridge